
// QUESTA FUNZIONE ACCETTA IN INPUT UN TIPO GENERICO E RESTITUISCE IN OUTPUT UN ARRAY DI TIPO GENERICO (STESSO TIPO DATO IN INPUT)
function asArray<T>(argument: T): T[] {    
  var arrayOfT: T[] = [];    // CREO UN ARRAY DEL TIPO T PASSATO IN INPUT
  arrayOfT.push(argument);   // INSERISCO L'ELEMENTO NELL'ARRAY
  return arrayOfT;
}

// CHIAMO LA FUNZIONE asArray PASSANTO UN OGGETTO STRINGA
var arrayFromString = asArray<string>("beep");
console.log(arrayFromString[0]);         // LOGGO IL VALORE DEL PRIMO ED UNICO ELEMENTO DELL'ARRAY RESITUITO DALLA FUNZIONE asArray
console.log(typeof arrayFromString[0])   // LOGGO IL TIPO DEL PRIMO ED UNICO ELEMENTO DELL'ARRAY RESITUITO DALLA FUNZIONE asArray

// CHIAMO LA FUNZIONE asArray PASSANTO UN OGGETTO NUMBER
var arrayFromNumber = asArray(42);
console.log(arrayFromNumber[0]);         // LOGGO IL VALORE DEL PRIMO ED UNICO ELEMENTO DELL'ARRAY RESITUITO DALLA FUNZIONE asArray
console.log(typeof arrayFromNumber[0])   // LOGGO IL TIPO DEL PRIMO ED UNICO ELEMENTO DELL'ARRAY RESITUITO DALLA FUNZIONE asArray